#!/bin/bash

# clears the marks that are stored

MACRO_FILE="/Users/Krystopher_Weeton/scripts/MACROS"

if [[ "$#" -ne 0 ]]; then
  echo "clrmacros does not take in any paramters"
  exit
fi

>$MACRO_FILE
