#!/bin/bash

# Removes the specified mark from the list of marks
#Check the proper number of arguments
if [[ "$#" -ne 2 ]]; then
  echo "USAGE: $0 <variable-name> <type>"
  exit
fi

VAR_NAME=$1
TYPE=$2
TAB="\t"

OUTPUT="\n
${VAR_NAME}Value: ${TYPE};\n
@Output() ${VAR_NAME}Change = new EventEmitter<${TYPE}>();\n
@Input()\n
get ${VAR_NAME}() {\n
${TAB}return this.${VAR_NAME}Value;\n
}\n
set ${VAR_NAME}(value) {\n
${TAB}this.${VAR_NAME}Change.emit(value);\n
${TAB}this.${VAR_NAME}Value = value;\n
}"

echo -e $OUTPUT | pbcopy
