#!/bin/bash

# Lists all current stored marks

INPUT_FILE="/Users/Krystopher_Weeton/scripts/MARKS"

GREEN="\033[0;32m"        # Green
NC='\033[0m'

while read p; do
	FIRST=1
	for w in $p; do
		if [[ FIRST -ne 1 ]]; then
			MARK=$w
		else
			DIRECTORY=$w
		fi
		FIRST=0
	done

	echo -e "${GREEN}${MARK}${NC}: ${DIRECTORY}"
done <$INPUT_FILE
