#!/bin/bash

# Opens a chrome window to the specified localhost port

# Check the proper number of arguments
if [[ "$#" -ne 1 ]]; then
    echo "USAGE: $0 <port>"
  exit
fi

open -a "Google Chrome" "http://localhost:$1"
