#!/bin/bash

MACRO_FILE="/Users/Krystopher_Weeton/scripts/MACROS"

if [[ "$#" -ne 2 ]]; then
    echo "USAGE: recordmacro <name> <commands>"
    exit
fi

echo $1 >> $MACRO_FILE
echo $2 >> $MACRO_FILE
